# Generated by Django 4.1 on 2022-08-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_alter_ciudad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiene',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.elemento', unique=True),
        ),
    ]
