# Generated by Django 4.1 on 2022-08-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_tiene_elemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiene',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.elemento'),
        ),
    ]
